# Generated by Django 3.0.8 on 2020-07-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200716_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='posts',
            new_name='content',
        ),
    ]
